// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row of the [`InsightsSummary`] activity-type breakdown. `activity` is the
 * vision-assigned label (only tagged frames are counted).
 */
export type ActivityCount = { activity: string | null, count: number, };
