// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A streamed chunk of an answer (`answer_delta` event / `AnswerProvider` channel).
 */
export type AnswerDelta = { "type": "thinking", text: string, } | { "type": "token", text: string, } | { "type": "citation", frame_id: number, } | { "type": "done" } | { "type": "error", message: string, };
