// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnswerDelta } from "./AnswerDelta";

/**
 * Request-scoped streamed answer event (`answer_delta` payload).
 */
export type AnswerEvent = { request_id: string, delta: AnswerDelta, };
