// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * State of the opt-in local HTTP API for the Settings panel (0.3.0 PR7; `03 §7c`,
 * D11) — the return of `get_api_status` / `set_api_config` / `regenerate_api_token`.
 * `enabled` is the persisted intent; `running` is whether the socket is actually
 * bound. The two diverge in exactly one case: `enabled && !running && last_error` is
 * the **loud guided-change** state — the port was in use on enable, so the server did
 * not start, the intent is preserved, and the Settings panel shows the warning + a
 * "pick another port" retry (mirrors the D6 hotkey-conflict pattern). `token` carries
 * the bearer token so Settings can reveal/copy it (`§7c`: "shown/copyable"); it is
 * `None` only before the first enable ever generated one. The token lives in the
 * `settings` KV table, **never** in the `Settings` struct, so it cannot leak through
 * `get_settings`.
 */
export type ApiStatus = { 
/**
 * Persisted intent — the master toggle.
 */
enabled: boolean, 
/**
 * Whether the HTTP server is currently bound and serving.
 */
running: boolean, 
/**
 * The configured port (default 43210); the bind is always `127.0.0.1`.
 */
port: number, 
/**
 * The bearer token (revealed/copied in Settings); `None` before first enable.
 */
token: string | null, 
/**
 * Why the server is not running despite `enabled` (e.g. "port 43210 in use").
 */
last_error: string | null, };
