// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row of the [`InsightsSummary`] top-apps breakdown. `app` is `None` for
 * frames with no resolved foreground app.
 */
export type AppCount = { app: string | null, count: number, };
