// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row of the per-app text-filter suppression metric (`get_text_filter_stats`
 * output, `03 §3b`). The guardrail that makes silent over-suppression observable:
 * `rate` = `suppressed_spans / total_spans` over frames classified by the live
 * `filter_version`. `app` (the foreground/target app) is `None` for frames with no
 * resolved foreground app. False suppression is the top risk, so this is surfaced
 * in the UI and recoverable via `include_chrome` + preserved `raw_text`.
 */
export type AppSuppression = { app: string | null, 
/**
 * Total classified spans for this app.
 */
total_spans: number, 
/**
 * Spans dropped from `content_text` (role `chrome`/`system`/`background`).
 */
suppressed_spans: number, 
/**
 * `suppressed_spans / total_spans`, in `[0,1]` (`0` when `total_spans == 0`).
 */
rate: number, };
