// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input to the `ask` command. The answer streams back via `answer_delta` events.
 */
export type AskRequest = { query: string, thinking: boolean, max_tokens: number, };
