// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input to the `ask` command. The answer streams back via request-scoped `answer_delta` events.
 */
export type AskRequest = { request_id: string | null, query: string, thinking: boolean, max_tokens: number, 
/**
 * Per-request retrieval-depth override (`03 §8` `retrieval.default_top_k`).
 * `None` → the configured default. `#[serde(default)]` so existing callers
 * that omit it keep working.
 */
top_k: number | null, };
