// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Emitted once per stored capture (`capture_tick` event).
 */
export type CaptureTick = { frame_id: number, captured_at: number, monitor_index: number, };
