// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a frame was captured (`docs/0.2.0.md` event-driven capture; `07` #47/#57).
 *
 * [`CaptureTrigger::Timer`] is the always-present 0.2.0 baseline cadence (and the
 * event-mode fallback); the other variants arrive only when the opt-in event-driven
 * capture mode is enabled. Persisted to `frames.capture_trigger` (`03 §4`) and
 * surfaced in [`crate::ipc::FrameDetail`] so the Moment view can show why a frame was
 * captured. It is a **label, never input content** — no keystrokes or clipboard text.
 */
export type CaptureTrigger =
  | "timer"
  | "idle"
  | "foreground_change"
  | "clipboard_change"
  | "typing_pause"
  | "click"
  | "scroll_stop"
  | "manual";
