// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentStatus } from "./ComponentStatus";

/**
 * Readiness of one subsystem: a [`ComponentStatus`] plus optional human-readable
 * `detail` (e.g. "model downloading 40%", "sidecar evicted (idle)", "WebView2
 * runtime missing") so the UI can explain *why* without a separate lookup.
 */
export type ComponentReadiness = { status: ComponentStatus, detail: string | null, };
