// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Readiness of a single subsystem.
 */
export type ComponentStatus = "unknown" | "initializing" | "ready" | "unavailable" | "error";
