// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Readiness state of a single subsystem.
 *
 * `03 §7` returns a `Readiness` but does not define this enum (07 gap #3). The
 * states below are a closed set chosen so the UI's readiness panel can show a
 * truthful, actionable status for every subsystem without inventing per-screen
 * vocabulary:
 * - `Unknown` — not yet probed (the honest pre-init value).
 * - `Disabled` — intentionally off via settings (e.g. capture stopped, image
 *   embeddings disabled, vision in `on_demand` and idle). Not an error.
 * - `Initializing` — coming up (DB migrating, model downloading/loading, sidecar
 *   spawning).
 * - `Ready` — operational (or, for the lazily-evicted sidecar, able to serve on
 *   demand).
 * - `Unavailable` — a prerequisite is missing (model not downloaded, sidecar
 *   binary absent, no capturable monitor). Actionable by the user.
 * - `Error` — a failure occurred; see `detail`.
 */
export type ComponentStatus = "unknown" | "disabled" | "initializing" | "ready" | "unavailable" | "error";
