// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of the `export_data` command (0.3.0 PR7; `03 §7c`, D12) — the streamed JSON
 * file the Settings "Export…" button produced. `path` is the absolute file path (in
 * the user's Downloads folder); `frames`/`marks` are the counts written; `bytes` is
 * the file size. The same streaming code path backs `GET /v1/export`, so the export
 * works even with the API disabled.
 */
export type ExportResult = { path: string, frames: number, marks: number, bytes: number, };
