// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input to the `export_data` command (0.3.0 PR7; `03 §7c`, D12). Bounds the export
 * to an optional half-open `[from, to)` window (unix epoch ms), matching the
 * `GET /v1/export?from=&to=` query. Both `None` (the Settings "Export…" button) =
 * full history.
 */
export type ExportRequest = { from: number | null, to: number | null, };
