// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Flash-attention mode for the llama.cpp sidecar (`--flash-attn`). `Auto` follows what
 * the bundled binary supports (it resolves to on when the flag exists, off otherwise);
 * `On`/`Off` force the choice. Flash attention reduces the attention compute buffer and
 * is a prerequisite for quantized KV cache.
 */
export type FlashAttnSetting = "auto" | "on" | "off";
