// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A lightweight frame reference for browsing — the `get_frames` and
 * `get_nearest_frame` outputs (P5). Carries only what a tile/thumbnail needs
 * (frame id, capture time, the stored JPEG's relative path, and the foreground
 * app hint), without the OCR text / vision / tags that [`FrameDetail`] hydrates.
 * Drives the Timeline hover thumbnails, the Deck "jump back in" recents, and a
 * Moment's neighbour context; open one with `get_frame(frame_id)` for full detail.
 */
export type FrameMeta = { frame_id: number, captured_at: number, image_path: string, app_hint: string | null, };
