// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { VisionAnalysis } from "./VisionAnalysis";

/**
 * Full detail for a single frame (`get_frame` output).
 */
export type FrameDetail = { frame_id: number, captured_at: number, monitor_index: number, width: number, height: number, image_path: string, app_hint: string | null, window_title: string | null, browser_url: string | null, activity_type: string | null, text: string | null, vision: VisionAnalysis | null, tags: Array<string>, };
