// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Registration state for a global hotkey managed by the shell (`overlay.hotkey`,
 * 0.3.0 PR5). `registered=false` is a first-class UI state so conflicts surface
 * loudly in Settings instead of silently disabling the shortcut (D6).
 */
export type HotkeyStatus = {
  id: string;
  chord: string;
  registered: boolean;
  error: string | null;
};
