// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActivityCount } from "./ActivityCount";
import type { AppCount } from "./AppCount";
import type { TimelineBucket } from "./TimelineBucket";

/**
 * Aggregate activity summary over a time window (`get_insights` output).
 *
 * The spec defines no Insights contract (silent gap, logged in `07`). This is the
 * chosen shape: real DB aggregates only — totals, capture density over time
 * (reusing [`TimelineBucket`]), the top foreground apps, and the vision
 * activity-type breakdown. [`Default`] is the honest-empty summary.
 */
export type InsightsSummary = { 
/**
 * Frames captured in the window.
 */
total_frames: number, 
/**
 * Frames in the window that carry a vision `activity_type`.
 */
tagged_frames: number, 
/**
 * Capture density across the window (sparse, ascending by time).
 */
captures: Array<TimelineBucket>, 
/**
 * Most-captured foreground apps, descending by frame count.
 */
top_apps: Array<AppCount>, 
/**
 * Vision activity-type breakdown, descending by frame count.
 */
activity_breakdown: Array<ActivityCount>, };
