// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobKind } from "./JobKind";
import type { JobStats } from "./JobStats";

/**
 * Data-changing enrichment job completion (`job_completed` event). Carries enough
 * identity for the UI to refresh frame/search/insights data surgically.
 */
export type JobCompleted = { job_id: number, kind: JobKind, frame_id: number, stats: JobStats, };
