// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Kind of deferred work. Serializes to the DB `kind` column
 * (`'embed_text' | 'embed_image' | 'vision_tag'`, `03 §4`).
 */
export type JobKind = "embed_text" | "embed_image" | "vision_tag";
