// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Kind of deferred work. Serializes to the DB `kind` column
 * (`'embed_text' | 'vision_tag'`, `03 §4`). The `embed_image` kind was removed in
 * 0.3.0 PR4 with the image-embedding lane; the V9 migration deletes any leftover rows.
 */
export type JobKind = "embed_text" | "vision_tag";
