// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobStats } from "./JobStats";

/**
 * Job-queue progress snapshot (`job_progress` event).
 */
export type JobProgress = { stats: JobStats, };
