// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Aggregate queue counts surfaced to the UI (`get_job_stats`, `03 §7`).
 */
export type JobStats = { pending: number, running: number, done: number, failed: number, dead: number, };
