// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * State of a job in the queue. Serializes to the DB `state` column
 * (`pending | running | done | failed | dead`, `03 §4/§5`).
 */
export type JobState = "pending" | "running" | "done" | "failed" | "dead";
