// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * KV-cache element type for the llama.cpp sidecar (`--cache-type-k`/`--cache-type-v`).
 * Lower precision shrinks the on-GPU KV cache (less VRAM) for a small quality cost.
 * `Q8_0` is a near-lossless default; `F16` is the no-compromise escape hatch; `Q4_0`
 * is the smallest. The `#[serde(rename)]`s pin the wire/TS strings to the exact tokens
 * `llama-server` expects, so a stored value is also the launch-arg value.
 */
export type KvCacheType = "f16" | "q8_0" | "q4_0";
