// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToastLevel } from "./ToastLevel";

/**
 * Payload of the overlay `mark_toast` event (0.3.0 PR6; `03 §7b`). Tells the overlay
 * window to show the quiet, non-focus-stealing "Marked ✓ — note?" confirmation (or a
 * warning on failure). `mark_id` is `Some` on success (so the optional note can be
 * attached via `set_mark_note`), `None` on the failure variant (e.g. capture off, or a
 * privacy-gate denial), where only the `message` is shown.
 */
export type MarkToast = { mark_id: number | null, level: ToastLevel, message: string, };
