// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A mark — a user-flagged moment with an optional intention note (`list_marks`
 * output, 0.3.0 PR6; `03 §4`/`§7b`). Carries the joined frame fields the Intentions
 * strip renders (thumbnail + context) so listing marks never triggers an N+1
 * `get_frame` per row; the `frames` INNER JOIN is total because `marks.frame_id`
 * CASCADEs with the frame. A retention-degraded frame keeps its row (image_purged =
 * true, "text kept"), so a mark survives image expiry (`03 §4`, D10).
 */
export type Mark = {
  mark_id: number;
  frame_id: number;
  /**
   * When the mark was created, unix epoch ms.
   */
  created_at: number;
  /**
   * Optional one-line intention note (attached via `set_mark_note` after the fact).
   */
  note: string | null;
  /**
   * `null` while unresolved; set when the user resolves or dismisses the mark.
   */
  resolved_at: number | null;
  /**
   * The marked frame's capture time, unix epoch ms (joined for display "age").
   */
  captured_at: number;
  image_path: string;
  image_purged: boolean;
  app_hint: string | null;
  window_title: string | null;
};
