// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Phase of a model download (`model_download` event). Drives the progress UI so a
 * multi-GB model fetch communicates progress + completion/error instead of just opaque
 * network activity (`03 §6/§7`).
 */
export type ModelDownloadPhase = "downloading" | "done" | "failed";
