// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User-selectable model tier per lane (`00 §E`). 0.3.0 retired the `Beta` tier
 * (both lanes uniformly Apache-2.0); a persisted `beta` selection maps to `quality`
 * on load, logged once + persisted (`03 §8`, `docs/0.3.0.md` PR3, D3/D4).
 */
export type ModelTier = "default" | "quality";
