// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelDownloadPhase } from "./ModelDownloadPhase";
import type { ModelLane } from "./ModelLane";

/**
 * Progress of a model download for one lane. `total_bytes` is `None` when the size could
 * not be probed (the UI then shows bytes-downloaded without a percentage). `error` is set
 * only on the `Failed` phase.
 */
export type ModelDownloadStatus = { lane: ModelLane, model: string | null, phase: ModelDownloadPhase, downloaded_bytes: number, total_bytes: number | null, error: string | null, };
