// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One of the two inference lanes (`03 §6`, `MODEL_REGISTRY`).
 */
export type ModelLane = "vision" | "answer";
