// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User-selectable model tier per lane (`00 §E`).
 */
export type ModelTier = "default" | "quality" | "beta";
