// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A connected monitor the capture source can see.
 */
export type MonitorInfo = { index: number, name: string, width: number, height: number, is_primary: boolean, };
