// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Event payload telling the main window to open a captured Moment after the overlay
 * accepts a result.
 */
export type OpenMoment = { frame_id: number };
