// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentStatus } from "./ComponentStatus";

/**
 * Aggregate readiness (`get_readiness` output / `readiness_changed` event).
 */
export type Readiness = { capture: ComponentStatus, db: ComponentStatus, embed_model: ComponentStatus, sidecar: ComponentStatus, };
