// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Output of `generate_report` (`03 §8b`). Markdown body + the frames cited, plus
 * auditable coverage/cost metadata so the UI footer states honestly what was read.
 */
export type ReportResponse = { markdown: string, 
/**
 * Frames the model actually read (deduped, in inclusion order).
 */
cited_frame_ids: Array<number>, 
/**
 * Human label for the covered range ("today", "the last 7 days", …).
 */
range_label: string, 
/**
 * Periods in range (active + empty).
 */
periods_total: number, 
/**
 * Active periods that were summarized.
 */
periods_covered: number, 
/**
 * Frames sampled into the map step.
 */
frames_sampled: number, 
/**
 * Frames actually summarized (== `cited_frame_ids.len()`).
 */
frames_summarized: number, 
/**
 * Total sidecar passes (map + reduce + final); `0` for a no-evidence report.
 */
passes: number, 
/**
 * A structural bound forced coarser sampling than requested (honest framing).
 */
truncated: boolean, 
/**
 * Resolved model identifier (GGUF filename) for the footer; `None` if empty.
 */
model: string | null, };
