// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReportKind } from "./ReportKind";
import type { TimeRange } from "./TimeRange";

/**
 * Input to the `generate_report` command (`03 §7`/`§8b`). Progress streams via
 * `report_progress` events scoped by `request_id`; the final value returns from
 * the awaited command. `prompt` (Custom only) steers the summary via semantic
 * retrieval; Daily/Weekly/Custom-without-prompt use temporal-coverage sampling.
 */
export type ReportRequest = { kind: ReportKind, time_range: TimeRange, prompt: string | null, request_id: string | null, };
