// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which range a recall report covers (`03 §8b`). The UI resolves the concrete
 * local `[start, end)` for every kind and sends it as `ReportRequest.time_range`;
 * `kind` selects the retrieval depth and the human range label, and gates the
 * coverage-vs-relevance retrieval path (`Custom` + a `prompt` → semantic).
 */
export type ReportKind = "daily" | "weekly" | "custom";
