// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Progress of an in-flight `generate_report` (`report_progress` event), scoped by
 * `request_id`. `stage` is a short human label ("Summarizing day 3 of 7",
 * "Combining summaries"); `done`/`total` drive a determinate progress bar.
 */
export type ReportProgress = { request_id: string, stage: string, done: number, total: number, };
