// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The last sustained work context before the current detour (`where_was_i` output,
 * 0.3.0 PR6; `03 §7b`, D9). `None` from the command means "nothing to resume yet".
 * The pure heuristic (`kernel::resume`) picks the most recent run of frames sharing a
 * context key that persisted ≥ `resume.min_dwell_secs`, excluding the current
 * (anchor) context, ScreenSearch itself, and `privacy.excluded_apps`. `frame_id` is
 * the run's representative (last) frame — `Enter`/click opens its Moment. `image_path`
 * and `image_purged` let the overlay/Deck render a thumbnail without a second
 * `get_frame`. `browser_url` is dormant today (always `None` in production capture).
 */
export type ResumeContext = {
  frame_id: number;
  /**
   * The representative frame's `app_hint`, original casing (the context's app).
   */
  app: string;
  window_title: string | null;
  browser_url: string | null;
  /**
   * First capture of the sustained run, unix epoch ms.
   */
  span_start: number;
  /**
   * Last capture of the sustained run (the representative frame), unix epoch ms.
   */
  span_end: number;
  image_path: string;
  image_purged: boolean;
};
