// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimeRange } from "./TimeRange";

/**
 * Input to the `search` command.
 */
export type SearchQuery = { text: string, limit: number, time_range: TimeRange | null, 
/**
 * Also search raw/app-chrome text, not just `content_text` (`03 §3b`). Default
 * `false` → retrieval over content text only. `#[serde(default)]` so a client
 * that omits it gets the safe default.
 */
include_chrome: boolean, };
