// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimeRange } from "./TimeRange";

/**
 * Input to the `search` command.
 */
export type SearchQuery = { text: string, limit: number, time_range: TimeRange | null, };
