// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One hybrid-search result row (`search` output).
 */
export type SearchHit = { frame_id: number, captured_at: number, snippet: string, score: number, image_path: string, app_hint: string | null, };
