// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionArtifactKind } from "./SessionArtifactKind";
import type { SessionArtifactRole } from "./SessionArtifactRole";

export type SessionArtifact = { id: number, session_id: number, kind: SessionArtifactKind, role: SessionArtifactRole | null, frame_id: number | null, content: string, created_at: number, };
