// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request-scoped in-app session Recap. Progress and cancellation reuse the existing
 * report request id machinery.
 */
export type SessionRecapRequest = { session_id: number, request_id: string | null, };
