// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionHost } from "./SessionHost";
import type { SessionKind } from "./SessionKind";

export type Session = { id: number, started_at: number, ended_at: number | null, kind: SessionKind, tool: string | null, host: SessionHost | null, context_key: string, title: string | null, summary: string | null, summary_model: string | null, confidence: number, frozen: boolean, created_at: number, updated_at: number, };
