// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionKind } from "./SessionKind";
import type { TimeRange } from "./TimeRange";

/**
 * Filters for the Timeline/session list. The command normalizes an empty `tool`
 * to no filter and defaults/clamps `limit` at the shell boundary.
 */
export type SessionQuery = { time_range: TimeRange | null, kind: SessionKind | null, tool: string | null, limit: number | null, };
