// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrameMeta } from "./FrameMeta";
import type { Session } from "./Session";
import type { SessionArtifact } from "./SessionArtifact";

/**
 * Session drill-in payload: bounded representative frames plus every extracted
 * exchange. `frame_count` remains the truthful total even when `frames` is sampled.
 */
export type SessionDetail = { session: Session, frames: Array<FrameMeta>, frame_count: number, exchanges: Array<SessionArtifact>, };
