// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionHost } from "./SessionHost";
import type { SessionKind } from "./SessionKind";

/**
 * Compact session identity joined onto frame and resume responses.
 */
export type SessionReference = { id: number, started_at: number, ended_at: number | null, kind: SessionKind, tool: string | null, host: SessionHost | null, title: string | null, confidence: number, };
