// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelLane } from "./ModelLane";
import type { ModelTier } from "./ModelTier";

/**
 * Input to `set_model_tier`.
 */
export type SetModelTier = { lane: ModelLane, tier: ModelTier, };
