// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelTier } from "./ModelTier";

/**
 * User-facing settings (`get_settings`/`set_settings`). Field defaults mirror
 * `03 §8`; persisted as key/value rows in the `settings` table.
 *
 * Deferred vision tagging is never real-time (`03 §5`). On-demand tagging
 * (UI-triggered) is always available; **timed** and **idle** enrichment are each
 * independent opt-in toggles, off by default, with a user-set threshold. (This
 * replaces `03 §8`'s single `enrich.vision_mode` enum — see specs/06_PATCH_PLAN.)
 *
 * `sidecar_device` is the optional llama.cpp `--device` selector (for example,
 * `Vulkan0`); `None` lets llama.cpp choose its default device.
 */
export type Settings = { capture_interval_ms: number, 
/**
 * Empty = all monitors.
 */
capture_monitors: Array<number>, capture_diff_threshold: number, storage_jpeg_quality: number, storage_max_width: number, 
/**
 * 0 = keep forever.
 */
storage_retention_days: number, enrich_embed_text: boolean, enrich_image_embeddings: boolean, 
/**
 * Opt-in: tag up to a batch of untagged frames every `vision_timer_interval_ms`.
 */
enrich_vision_timer_enabled: boolean, enrich_vision_timer_interval_ms: number, 
/**
 * Opt-in: tag while the user has been idle for at least `vision_idle_secs`.
 */
enrich_vision_idle_enabled: boolean, enrich_vision_idle_secs: number, 
/**
 * Max still-untagged frames a timer/idle tick enqueues per run (the scheduler
 * batch size). Already-queued frames are skipped, so this caps fresh work per run.
 */
enrich_vision_batch_size: number, enrich_worker_concurrency: number, models_vision_tier: ModelTier, models_answer_tier: ModelTier, answer_thinking: boolean, sidecar_idle_ttl_secs: number, sidecar_ngl: number, sidecar_device: string | null, privacy_excluded_apps: Array<string>, privacy_pause_on_lock: boolean, };
