// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlashAttnSetting } from "./FlashAttnSetting";
import type { KvCacheType } from "./KvCacheType";
import type { ModelTier } from "./ModelTier";

/**
 * User-facing settings (`get_settings`/`set_settings`). Field defaults mirror
 * `03 §8`; persisted as key/value rows in the `settings` table.
 *
 * Deferred vision tagging is never real-time (`03 §5`). On-demand tagging
 * (UI-triggered) is always available; **timed** and **idle** enrichment are each
 * independent opt-in toggles, off by default, with a user-set threshold. (This
 * replaces `03 §8`'s single `enrich.vision_mode` enum — see specs/06_PATCH_PLAN.)
 *
 * `sidecar_device` is the optional llama.cpp `--device` selector (for example,
 * `Vulkan0`); `None` lets llama.cpp choose its default device.
 */
export type Settings = { capture_interval_ms: number, 
/**
 * Empty = all monitors.
 */
capture_monitors: Array<number>, capture_diff_threshold: number, storage_jpeg_quality: number, storage_max_width: number, 
/**
 * 0 = keep forever.
 */
storage_retention_days: number, enrich_embed_text: boolean, enrich_image_embeddings: boolean, 
/**
 * Opt-in: tag up to a batch of untagged frames every `vision_timer_interval_ms`.
 */
enrich_vision_timer_enabled: boolean, enrich_vision_timer_interval_ms: number, 
/**
 * Opt-in: tag while the user has been idle for at least `vision_idle_secs`.
 */
enrich_vision_idle_enabled: boolean, enrich_vision_idle_secs: number, 
/**
 * Max still-untagged frames a timer/idle tick enqueues per run (the scheduler
 * batch size). Already-queued frames are skipped, so this caps fresh work per run.
 */
enrich_vision_batch_size: number, enrich_worker_concurrency: number, models_vision_tier: ModelTier, models_answer_tier: ModelTier, answer_thinking: boolean, sidecar_idle_ttl_secs: number, sidecar_ngl: number, sidecar_device: string | null, 
/**
 * Sidecar context window in tokens (`--ctx-size`). `0` = automatic: a small
 * per-lane default (vision 4096, answer 8192). A non-zero value overrides both
 * lanes. Lower = less VRAM (smaller KV cache); too low can truncate long answers.
 */
sidecar_ctx_size: number, 
/**
 * KV-cache precision (`--cache-type-k`/`--cache-type-v`). A quantized cache uses
 * less VRAM and is applied only when flash attention is active.
 */
sidecar_kv_cache_type: KvCacheType, 
/**
 * Flash-attention mode (`--flash-attn`). Reduces attention memory and unlocks KV
 * quantization; `Auto` enables it when the bundled binary supports it.
 */
sidecar_flash_attn: FlashAttnSetting, privacy_excluded_apps: Array<string>, privacy_pause_on_lock: boolean, 
/**
 * Default value of the Recall search "include app chrome / raw text" toggle
 * (`03 §8` `text.include_chrome_default`). `false` → default search uses
 * `content_text` only; the per-query `SearchQuery.include_chrome` can still opt in.
 */
text_include_chrome_default: boolean, 
/**
 * Appearances of a span signature before it is marked static chrome and dropped
 * from `content_text` (`03 §8` `text.chrome_suppress_min_seen`). A threshold, never
 * hardcoded (`03 §3b`).
 */
text_chrome_suppress_min_seen: number, 
/**
 * Lines at least this many characters are never suppressed for merely repeating
 * (`03 §8` `text.chrome_protect_min_chars`) — protects long, information-rich text.
 */
text_chrome_protect_min_chars: number, 
/**
 * Grid resolution for a span's `region_bucket` in the chrome signature
 * (`03 §8` `text.chrome_region_buckets`); an N×N grid over the normalized frame.
 */
text_chrome_region_buckets: number, 
/**
 * Default Ask retrieval depth (`03 §8` `retrieval.default_top_k`), replacing the
 * former hardcoded `ASK_TOP_K`. The per-request `AskRequest.top_k` overrides it.
 */
retrieval_default_top_k: number, 
/**
 * Recall-report target sampled frames **per active period** (`03 §8`
 * `reports.daily_top_k`). Report depth scales as this × active periods (`§8b`).
 */
reports_daily_top_k: number, 
/**
 * Recall-report **global** cap on frames summarized across all periods
 * (`03 §8` `reports.weekly_top_k`); bounds the sidecar pass count on weak HW.
 */
reports_weekly_top_k: number, 
/**
 * Frame count at/below which a report uses a single pass; above it, map-reduce
 * (`03 §8` `reports.map_reduce_min_frames`, `§8b`).
 */
reports_map_reduce_min_frames: number, 
/**
 * Event-driven capture master switch (`capture.event_driven_enabled`,
 * `docs/0.2.0.md`). Opt-in, default `false`: capture stays the 0.2.0 timer/idle
 * cadence and no input hooks are installed unless this is on.
 */
capture_event_driven_enabled: boolean, 
/**
 * Capture on foreground/app switch when event-driven capture is on
 * (`capture.event_on_foreground`).
 */
capture_event_on_foreground: boolean, 
/**
 * Capture on clipboard change — change event only, never contents
 * (`capture.event_on_clipboard`).
 */
capture_event_on_clipboard: boolean, 
/**
 * Capture when the user goes idle past the threshold (`capture.event_on_idle`).
 */
capture_event_on_idle: boolean, 
/**
 * Capture when typing/input pauses for the quiet period
 * (`capture.event_on_typing_pause`).
 */
capture_event_on_typing_pause: boolean, 
/**
 * Capture on a mouse click — the *fact* of a click only, never position/button/
 * content (`capture.event_on_click`). Uses the `WH_MOUSE_LL` low-level mouse hook.
 */
capture_event_on_click: boolean, 
/**
 * Capture when scrolling stops after a wheel burst settles
 * (`capture.event_on_scroll_stop`). Uses the `WH_MOUSE_LL` low-level mouse hook.
 */
capture_event_on_scroll_stop: boolean, 
/**
 * Collapse a burst of triggers within this window into one capture, ms
 * (`capture.event_debounce_ms`). A threshold, never hardcoded.
 */
capture_event_debounce_ms: number, 
/**
 * Minimum gap between any two event-driven captures, ms — the rate ceiling
 * (`capture.event_min_interval_ms`).
 */
capture_event_min_interval_ms: number, 
/**
 * Quiet period after the last input that counts as a typing pause, ms
 * (`capture.event_typing_pause_ms`).
 */
capture_event_typing_pause_ms: number, 
/**
 * Idle time that counts as "gone idle", ms (`capture.event_idle_threshold_ms`).
 */
capture_event_idle_threshold_ms: number, 
/**
 * Fallback capture interval in event mode, ms — a static screen is still sampled
 * at least this often (`capture.event_fallback_interval_ms`).
 */
capture_event_fallback_interval_ms: number, 
/**
 * Use Windows UI Automation for the target window's text, with OCR fallback
 * (`capture.uia_text_enabled`, `docs/0.2.0.md` #48). Default ON: UIA yields more
 * structured text than OCR; on any failure/timeout/thin-yield the frame falls back to
 * OCR. Hot-applies per frame (no capture restart).
 */
capture_uia_text_enabled: boolean, 
/**
 * Per-frame UIA latency budget, ms (`capture.uia_latency_budget_ms`). The tree walk
 * abandons past this and a 2× hard timeout guards a wedged worker; over budget → OCR
 * fallback. A threshold, never hardcoded. Baked into the provider at startup — applied
 * on app restart (a capture stop/start reuses the existing provider).
 */
capture_uia_latency_budget_ms: number, 
/**
 * Minimum UIA text length, chars, below which the read is a thin yield → OCR fallback
 * (`capture.uia_min_text_chars`). Catches GPU/canvas/custom-drawn windows where OCR is
 * strictly better. Baked into the provider at startup — applied on app restart (a
 * capture stop/start reuses the existing provider).
 */
capture_uia_min_text_chars: number, };
