// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelTier } from "./ModelTier";
import type { VisionMode } from "./VisionMode";

/**
 * User-facing settings (`get_settings`/`set_settings`). Field defaults mirror
 * `03 §8`; persisted as key/value rows in the `settings` table.
 */
export type Settings = { capture_interval_ms: number, 
/**
 * Empty = all monitors.
 */
capture_monitors: Array<number>, capture_diff_threshold: number, storage_jpeg_quality: number, storage_max_width: number, 
/**
 * 0 = keep forever.
 */
storage_retention_days: number, enrich_embed_text: boolean, enrich_image_embeddings: boolean, enrich_vision_mode: VisionMode, enrich_vision_timer_interval_ms: number, enrich_vision_idle_secs: number, enrich_worker_concurrency: number, models_vision_tier: ModelTier, models_answer_tier: ModelTier, answer_thinking: boolean, sidecar_idle_ttl_secs: number, sidecar_ngl: number, privacy_excluded_apps: Array<string>, privacy_pause_on_lock: boolean, };
