// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SidecarState } from "./SidecarState";

/**
 * Sidecar status update (`sidecar_status` event).
 */
export type SidecarStatus = { state: SidecarState, model: string | null, };
