// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle state of the inference sidecar (`03 §6`).
 */
export type SidecarState = "stopped" | "starting" | "ready" | "evicted" | "crashed";
