// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelLane } from "./ModelLane";
import type { SidecarState } from "./SidecarState";

/**
 * Sidecar status update (`sidecar_status` event). `lane` says which model is (or was
 * last) resident — vision vs. answer — so the UI can label the engine truthfully instead
 * of guessing from the filename. `None` when no model has loaded yet.
 */
export type SidecarStatus = { state: SidecarState, model: string | null, lane: ModelLane | null, };
