// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Storage footprint shown in the StatusRail.
 */
export type StorageStats = { db_bytes: number, frame_bytes: number, total_bytes: number, };
