// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a span was excluded from `content_text` (`03 §3b`). `Option<SuppressReason>`
 * maps to the nullable `text_spans.suppress_reason` column — `None` = a searchable,
 * non-suppressed span (no redundant in-enum `None` variant, `03 §4`).
 */
export type SuppressReason = "static_chrome" | "system_ui" | "background_window";
