// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SuppressReason } from "./SuppressReason";
import type { TextRole } from "./TextRole";
import type { TextSource } from "./TextSource";

/**
 * One OCR/UIA text span with normalized `[0,1]` geometry (`03 §3b`). Carried on
 * [`OcrResult::spans`] and persisted to `text_spans` (`03 §4`). Also surfaced over the
 * typed IPC boundary by `get_frame_spans` so the UI can render a crisp text+layout
 * **reconstruction** of a frame whose screenshot has been retention-degraded (the
 * stored geometry + role is enough to redraw what was on screen — "text is enough" as
 * durable proof).
 */
export type TextSpan = { 
/**
 * The recognized text, verbatim.
 */
text: string, 
/**
 * Normalized form used for chrome-signature matching (`03 §3b`,
 * [`normalize_text`]).
 */
normalized_text: string, source: TextSource, role: TextRole, 
/**
 * Normalized `[0,1]` bounding box (origin top-left), relative to the
 * full-resolution frame the OCR ran on.
 */
x: number, y: number, w: number, h: number, 
/**
 * Zero-based index of the OCR line this word belongs to (`Lines()` order). The
 * engine groups words into lines; carrying the index lets PR3's classifier group
 * spans back into lines exactly (no geometry heuristic) for line-level chrome
 * signatures and `content_text` reassembly (`03 §3b`).
 */
line_index: number, 
/**
 * Whether the span is included in searchable text. PR2 marks every span
 * searchable; PR3 sets this from the classified role.
 */
is_searchable: boolean, suppress_reason: SuppressReason | null, };
