// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Origin of a text span / the primary text of a frame (`03 §3b`). Serializes to
 * the DB `source` / `primary_source` columns (`'ocr' | 'uia'`, `03 §4`). UIA is
 * modelled now but only produced from 0.2.1 (`07` #48); 0.2.0 OCR is always `Ocr`.
 */
export type TextSource = "ocr" | "uia";
