// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Classified role of a text span (`03 §3b`). Serializes to the DB `role` column
 * (`03 §4` CHECK). PR2 emits every span as [`TextRole::Unknown`]; PR3's classifier
 * assigns the real roles and drops non-`content` spans from `content_text`.
 */
export type TextRole = "content" | "chrome" | "background" | "system" | "unknown";
