// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PressureSample } from "./PressureSample";

/**
 * Current state of the enrichment throttle (`get_throttle_status` command + the
 * `throttle_changed` event, `03 §7`). `level` is `0` Normal / `1` High (heavy
 * enrichment paused) / `2` Sustained (text-embed concurrency floored). `sample` is
 * `None` until the first probe reading lands; `gpu_monitored` mirrors the probe so the
 * UI can show an honest "GPU not monitored" state even before a sample exists.
 */
export type ThrottleStatus = {
  enabled: boolean;
  level: number;
  sample: PressureSample | null;
  gpu_monitored: boolean;
};
