// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Half-open `[start, end)` time window (start inclusive, end exclusive), unix
 * epoch milliseconds. `Store::hybrid_search` filters with `captured_at >= start
 * AND captured_at < end`, so callers must pass an exclusive upper bound — a frame
 * captured exactly at `end` is *not* included.
 */
export type TimeRange = { start: number, end: number, };
