// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Half-open time window, unix epoch milliseconds.
 */
export type TimeRange = { start: number, end: number, };
