// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One bucket of the timeline histogram (`get_timeline` output).
 */
export type TimelineBucket = { start: number, end: number, count: number, };
