// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ToastLevel } from "./ToastLevel";

/**
 * A transient user-facing notification (`toast` event).
 */
export type Toast = { level: ToastLevel, message: string, };
