// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Severity of a UI toast (`toast` event).
 */
export type ToastLevel = "info" | "success" | "warning" | "error";
