// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionReference } from "./SessionReference";

/**
 * Tauri-only where-was-i response. HTTP/MCP retain the shipped `ResumeContext`
 * object; the in-app command receives the same flattened fields plus session context.
 */
export type UiResumeContext = { session: SessionReference | null, frame_id: number, 
/**
 * The representative frame's `app_hint`, original casing (the context's app).
 */
app: string, window_title: string | null, browser_url: string | null, 
/**
 * First capture of the sustained run, unix epoch ms.
 */
span_start: number, 
/**
 * Last capture of the sustained run (the representative frame), unix epoch ms.
 */
span_end: number, image_path: string, image_purged: boolean, };
