// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Auto-update lifecycle (0.3.2 PR2, #69; `03 §11b`). Output of `get_update_status` /
 * `check_for_updates` and the payload of the `update_status_changed` event. The updater
 * is **pull-based and quiet** (D1): `Idle` means no update is known — the UI renders
 * **zero** updater presence (not a "no update" badge). `Available` / `Downloading` /
 * `Ready` are the only states with any UI surface (a quiet NavRail dot + an App-section
 * line); `Ready` installs **only** on a user-initiated restart. `Error` shows a quiet
 * App-section line + retry, never a modal. Deliberately carries no byte-progress — the
 * contract asks for presence, not a meter, and keeps the event stream sparse.
 */
export type UpdateStatus = { "state": "idle" } | { "state": "checking" } | { "state": "available", version: string, } | { "state": "downloading", version: string, } | { "state": "ready", version: string, } | { "state": "error", message: string, };
