// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Target of an `enqueue_vision` request: a single frame or a time range.
 */
export type VisionTarget = { "kind": "frame", frame_id: number, } | { "kind": "range", start: number, end: number, };
