// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Deferred vision-tagging output for a frame.
 */
export type VisionAnalysis = { description: string, activity_type: string | null, app_hint: string | null, confidence: number, model: string, };
