// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * When deferred vision tagging is allowed to run (`03 §5/§8`).
 * Never real-time — only on-demand, on a timer, or when the user is idle.
 */
export type VisionMode = "on_demand" | "timer" | "idle";
