// Barrel for the domain components (UI_REFERENCE §5). Import from here:
//   import { FrameTile, ScanlineTimeline } from "../domain";
export { FrameImage, type FrameImageProps } from "./FrameImage";
export { FrameTile, type FrameTileProps } from "./FrameTile";
export { SearchResult, type SearchResultProps } from "./SearchResult";
export { AnswerStream, type AnswerStreamProps } from "./AnswerStream";
export { CitationTile, type CitationTileProps } from "./CitationTile";
export { PromptCardGrid, type PromptCardGridProps } from "./PromptCardGrid";
export { ReportBuilder, type ReportBuilderProps } from "./ReportBuilder";
export { ReportView, type ReportViewProps } from "./ReportView";
export { JobQueueMeter, type JobQueueMeterProps } from "./JobQueueMeter";
export { ScanlineTimeline, type ScanlineTimelineProps } from "./ScanlineTimeline";
export { TimelineMinimap, type TimelineMinimapProps } from "./TimelineMinimap";
export { MomentDetail, type MomentDetailProps } from "./MomentDetail";
export { ModelTierPicker, type ModelTierPickerProps } from "./ModelTierPicker";
export { ModelPanel } from "./ModelPanel";
export { ScheduleControl, type ScheduleControlProps } from "./ScheduleControl";
export { RetentionControl, type RetentionControlProps } from "./RetentionControl";
export { InsightsBars, type InsightsBarsProps, type RankedItem } from "./InsightsBars";
export { CapturesTrend, type CapturesTrendProps } from "./CapturesTrend";
